const types = {
    FINISH_INTRO: "FINISH_INTRO",
    FETCHED_CONFIGS_SUCCESS: "FETCHED_CONFIGS_SUCCESS",
    FETCHED_CONFIGS_ERROR: "FETCHED_CONFIGS_ERROR",
    COUNT_OPEN_APP: "OPEN_APP",
    ON_RATED_APP: "ON_RATED_APP",
    UPDATE_CONFIGS: 'UPDATE_CONFIGS',
    UPDATE_FCM_TOKEN: 'UPDATE_FCM_TOKEN',
    SEND_FCM_TOKEN_TO_SERVER: 'SEND_FCM_TOKEN_TO_SERVER',
}
export default types
